fixtures:
  forge_modules:
    accounts: "puppetlabs/accounts"
    mysql: "puppetlabs/mysql"
    bdii: "cnafsd/bdii"
    firewall: "puppetlabs/firewall"
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
