fixtures:
  forge_modules:
    accounts: "puppetlabs/accounts"
    mysql: "puppetlabs/mysql"
    bdii: "CERNOps/bdii"
    firewall: "puppetlabs/firewall"
    concat: "puppetlabs/concat"
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
