---
Gemfile:
  required:
    ':development':
      - gem: nokogiri
      - gem: rspec-puppet-utils
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 80
  mock_with: ':rspec'
Rakefile:
  requires:
    puppet-strings-tasks: 'puppet-strings/tasks'