apiVersion: v1
kind: Pod
metadata:
    abels:
        ci-job: storm-puppet-module-tests
spec:
    nodeSelector:
        zone: ci
    containers:
      - name: docker-rspec-puppet
        image: italiangrid/docker-rspec-puppet:ci
        imagePullPolicy: Always
        command:
          - cat
        tty: true
        resources:
            limits:
                memory: 700Mi
                cpu: 1
      - name: jnlp
        resources:
            limits:
                memory: 700Mi
                cpu: 1
    restartPolicy: Never
