apiVersion: v1
kind: Pod
metadata:
    abels:
        ci-job: storm-puppet-module-tests
spec:
    nodeSelector:
        zone: ci
    volumes:
      - name: docker
        hostPath:
            path: /var/run/docker.sock
      - name: registry
        secret:
            secretName: registry-auth-basic
    containers:
      - name: docker-rspec-puppet
        image: cloud-vm114.cloud.cnaf.infn.it/italiangrid/kube-docker-runner:latest
        imagePullPolicy: Always
        command:
          - cat
        tty: true
        volumeMounts:
          - name: docker
            mountPath: /var/run/docker.sock
          - name: registry
            mountPath: /home/jenkins/.docker
        resources:
            limits:
                memory: 700Mi
                cpu: 1
      - name: jnlp
        resources:
            limits:
                memory: 700Mi
                cpu: 1
    restartPolicy: Never
